networks:
  default: localnet
  localnet:
    url: "http://127.0.0.1:4000/api"
    leader_only: false
  studionet:
    url: "https://studio.genlayer.com/api"
    leader_only: false

paths:
  contracts: "contracts"
  artifacts: "artifacts"

environment: .env
